// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBasePath() {
  return window['go']['main']['App']['GetBasePath']();
}

export function GetDefaultSiteRoot() {
  return window['go']['main']['App']['GetDefaultSiteRoot']();
}

export function GetServices() {
  return window['go']['main']['App']['GetServices']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSites() {
  return window['go']['main']['App']['GetSites']();
}

export function GetWWWPath() {
  return window['go']['main']['App']['GetWWWPath']();
}

export function OpenBrowser() {
  return window['go']['main']['App']['OpenBrowser']();
}

export function OpenSiteFolder(arg1) {
  return window['go']['main']['App']['OpenSiteFolder'](arg1);
}

export function OpenSiteInBrowser(arg1, arg2) {
  return window['go']['main']['App']['OpenSiteInBrowser'](arg1, arg2);
}

export function OpenWWWFolder() {
  return window['go']['main']['App']['OpenWWWFolder']();
}

export function RestartAll() {
  return window['go']['main']['App']['RestartAll']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetMinimizeToTray(arg1) {
  return window['go']['main']['App']['SetMinimizeToTray'](arg1);
}

export function StartAll() {
  return window['go']['main']['App']['StartAll']();
}

export function StartService(arg1) {
  return window['go']['main']['App']['StartService'](arg1);
}

export function StopAll() {
  return window['go']['main']['App']['StopAll']();
}

export function StopService(arg1) {
  return window['go']['main']['App']['StopService'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpdateSites(arg1) {
  return window['go']['main']['App']['UpdateSites'](arg1);
}
