// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';
import {main} from '../models';

export function GetBasePath():Promise<string>;

export function GetDefaultSiteRoot():Promise<string>;

export function GetServices():Promise<Array<services.ServiceInfo>>;

export function GetSettings():Promise<main.AppSettings>;

export function GetSites():Promise<Array<services.SiteConfig>>;

export function GetWWWPath():Promise<string>;

export function OpenBrowser():Promise<void>;

export function OpenSiteFolder(arg1:string):Promise<void>;

export function OpenSiteInBrowser(arg1:string,arg2:number):Promise<void>;

export function OpenWWWFolder():Promise<void>;

export function RestartAll():Promise<void>;

export function SelectDirectory():Promise<string>;

export function SetMinimizeToTray(arg1:boolean):Promise<void>;

export function StartAll():Promise<void>;

export function StartService(arg1:string):Promise<void>;

export function StopAll():Promise<void>;

export function StopService(arg1:string):Promise<void>;

export function UpdateSettings(arg1:main.AppSettings):Promise<void>;

export function UpdateSites(arg1:Array<services.SiteConfig>):Promise<void>;
